name: Create PKI provider configuration 
version: 2
testcases:
- name: create_pki_provider_config
  steps:
  - type: http
    method: POST
    url: '{{.pfserver_webadmin_url}}/api/v1/config/pki_providers'
    ignore_verify_ssl: true
    body: >-
      {
        "ca_cert_path": "/usr/local/pf/raddb/certs/ca.pem",
        "cn_attribute": "pid",
        "cn_format": "%s",
        "country": "CA",
        "host": "127.0.0.1",
        "id": "PacketFence-PKI",
        "locality": "Montreal",
        "organization": "Inverse",
        "password": null,
        "port": "9393",
        "postalcode": "H3N 1X1",
        "profile": 1,
        "proto": "https",
        "revoke_on_unregistration": null,
        "server_cert_path": "/usr/local/pf/raddb/certs/server.crt",
        "state": "Quebec",
        "streetaddress": "7000 park avenue",
        "type": "packetfence_pki",
        "username": null
      }
    headers:
      "Authorization": "{{.pfserver_token}}"
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 201
