name: Create PKI provisioner configuration 
version: 2
testcases:
- name: create_pki_provisioner_config
  steps:
  - type: http
    method: POST
    url: '{{.pfserver_webadmin_url}}/api/v1/config/provisionings'
    ignore_verify_ssl: true
    body: >-
      {
        "apply_role": "disabled",
        "autoregister": "disabled",
        "broadcast": "1",
        "can_sign_profile": null,
        "category": [
          "dot1x_eap_tls"
        ],
        "cert_chain": null,
        "certificate": null,
        "company": null,
        "description": "PacketFence-PKI",
        "dpsk": null,
        "eap_type": "13",
        "enforce": "enabled",
        "id": "Windows-PKI",
        "non_compliance_security_event": null,
        "oses": [],
        "passcode": null,
        "pki_provider": "PacketFence-PKI",
        "private_key": null,
        "psk_size": 8,
        "role_to_apply": null,
        "security_type": "WPA2",
        "server_certificate_path": null,
        "ssid": "PF-Secure",
        "sync_pid": "disabled",
        "type": "windows"
      }
    headers:
      "Authorization": "{{.pfserver_token}}"
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 201
