- hosts: service_rsyslog
  name: Manage rsyslog service
  become: True

  collections:
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03

  roles:
    - role: rsyslog
